### ISSUE TITLE
Allow use of whole connection string

### ISSUE THREAD

**Issue by dsyme** [isaacabraham/AzureStorageTypeProvider#44]
It would be nice if the type provider just allowed a single connection string like this, which is what Azure gives you in some instances:

    type Account = AzureTypeProvider<"DefaultEndpointsProtocol=https;AccountName=nameOfStorage;AccountKey=AHIUDMNWIKCSMNSCI(*WN"NC(*E==">

(That's not my real connection string :) )

**Comment by isaacabraham** [comment]
True. Is it possible to overload type provider arguments so that we can supply either the full connection string or the existing form of name / key?

**Comment by dsyme** [comment]
Sort of - you can either just make the second optional and "work it out" from the first argument (the JSON and XML type providers do this), or encourage people to use named arguments, ``STP<Account="abc¬,Key="def">`` and ``STP<ConnectionString="nnnnn">``
